from shapes import *

if __name__ == "__main__":
    hideturtle()
    shape("turtle")
    up()
    goto(-75, 75)
    showturtle()
    draw_equilateral_triangle(2, 50, False)
    hideturtle()
    goto(0, 75)
    showturtle()
    draw_square(2, 45, True, "red", "orange")
    hideturtle()
    goto(85, 75)
    showturtle()
    draw_pentagon(2, 30, True, "blue", "green")
    hideturtle()
    goto(-70, 0)
    showturtle()
    draw_hexagon(2, 30, False)
    hideturtle()
    goto(10, 0)
    showturtle()
    draw_octagon(2, 21, True, "black", "purple")
    hideturtle()
    goto(80, 0)
    showturtle()
    draw_star(2, 25, True, "orange", "gold")
    hideturtle()
    goto(33, -75)
    showturtle()
    draw_circle(2, 30, False, "red", "red")
    hideturtle()