from shapes import *

if __name__ == "__main__":
    hideturtle()
    shape("turtle")
    up()
    goto(-75, 75)
    showturtle()
    draw_equilateral_triangle(2, 50, "black", "blue")
    hideturtle()
    goto(0, 75)
    showturtle()
    draw_square(2, 45, "black", "red")
    hideturtle()
    goto(85, 75)
    showturtle()
    draw_pentagon(2, 30, "black", "orange")
    hideturtle()
    goto(-70, 0)
    showturtle()
    draw_hexagon(2, 30, "black", "yellow")
    hideturtle()
    goto(10, 0)
    showturtle()
    draw_octagon(2, 21, "black", "purple")
    hideturtle()
    goto(80, 0)
    showturtle()
    draw_star(2, 25, "black", "gold")
    hideturtle()
    goto(35, -75)
    showturtle()
    draw_circle(2, 27, "black", "green")
    hideturtle()